export const CHANGE_PASSWORD_REQUEST='CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS='CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILURE='CHANGE_PASSWORD_FAILURE';

export const FETCH_USER_REQUEST='FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS='FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE='FETCH_USER_FAILURE';